version: '3.1'

services:
  main-phpmyadmin:
    image: phpmyadmin:5.2.0
    ports:
    - "8201:80"
    environment:
      PMA_PORT: ${DB_PORT}
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
